### PR TITLE
update license and add license on the shapefile

### PR DESCRIPTION
**Pull request by meomancer**
this fix https://github.com/healthsites/healthsites/issues/1427

hi @timlinux 
can you review this PR, mostly for the content of license
what i changes
- add data credits on readme : https://github.com/healthsites/healthsites/compare/develop...meomancer:1427-odbl-license?expand=1#diff-04c6e90faac2675aa89e2176d2eec7d8R30
- add license.txt that will be included into shapefile zip https://github.com/meomancer/healthsites/blob/d539701bd0ad1ab0074f6360582cdd05309364af/django_project/api/LICENSE.txt
- add readme.md that will be included into shapefile.zip
https://github.com/meomancer/healthsites/blob/d539701bd0ad1ab0074f6360582cdd05309364af/django_project/api/README.md
- When on basemap esri, add "data license" on the attribution for osm
https://github.com/healthsites/healthsites/compare/develop...meomancer:1427-odbl-license?expand=1#diff-cc690b32b1b9c0a9c51bdecd0f2b7591R23

Example of zipped shapefiles
[China.zip](https://github.com/healthsites/healthsites/files/4543793/China.zip)

### CODE REVIEW

**Comment by timlinux** [comment]
@meomancer thanks

I think we should write a plain text document and not markdown which is probably a bit nerdy for many users. It can be as follows:


```
Provenance:

This data was generated as an extract from the OpenStreetMap global open database
(http://openstreetmap.org) by the Healthsites.io (http://healthsites.io) project. 

Caveats:

This data is an extract from OpenStreetMap and may differ in part or substantially from the
current state of the upstream OpenStreetMap project. In particular, entities deleted in 
OpenStreetMap may still be present in this extract, and changes to entities in OpenStreetMap
may not yet be reflected in this extract.

Healthsites.io provides these extracts as a convenience to people and organizations 
interested in supporting access to healthcare. In addition to the provisions laid out
in the ODBL license, Healthsites.io takes no responsibility for any inadequacies in the
data provided here. All data is provided on a best effort basis. 



Please make sure to credit the OpenStreetMap project whenever using this data using the text 
in the 'data credits' section below. Although not required, we would appreciate it if you 
additionally mention the HealthSites.io project (and link to our web site at http://healthsites.io) when citing this
data - it will help to support and publicise our work.

License

Data: Open Database License http://opendatacommons.org/licenses/odbl/ - see accompanying LICENSE.txt 
    file for a complete copy of this license.
Data credits : © OpenStreetMap contributors (http://www.openstreetmap.org/copyright)

Our intention is to foster widespread usage of the data that we provide. 
Please use this data in the interests of humanity and not for nefarious purposes.
```

CC @markherringer

**Comment by meomancer** [comment]
hi @timlinux 
like this? https://github.com/healthsites/healthsites/blob/b0e694163665e4e5b27e84c02b01f820db3c0e1a/django_project/api/README.md

**Comment by timlinux** [comment]
@meomancer perfect - just add a : after the license heading for consistency please.

Will you regenerate the extracts after deploying?

**Comment by meomancer** [comment]
hi @timlinux 
updated and deployed
currently, all shapefile are being regenerated

**Comment by markherringer** [comment]
@timlinux @meomancer I've made copy changes above. 

Let's prioritse https://github.com/healthsites/healthsites/issues/1355

**Pull request merged**
