### PR TITLE
#258 #118 #261 #217 #264 #216 #265 #263 | edit and create locality

### PR DESCRIPTION
**Pull request by meomancer**
@timlinux @markherringer 
this PR contains editing and adding locality, based attrbute on the webpage.
There is attribute that i am still confuse:
1. User can add 1 or more url?
2. what is "
Note: Outpatient consultation and in-patient hospitalization"

This is screenshot:
i did 2 scenario, edit and create
EDIT
-------------------------------------------------------------------------------------------------------------------------

selection_001
Want to edit "Puskesmas Kelambu"

selection_002
It will show editing form

selection_003
put data

selection_004
This is the edited data

CREATE
-------------------------------------------------------------------------------------------------------------------------
selection_005
When create, it will show empty form

selection_006
I move the market to south africa, filling the form

selection_007
After it is saved

screenshot from 2015-12-22 15 39 43
It will be shown on search

### CODE REVIEW

**Comment by timlinux** [comment]
Looking very nice @meomancer 

Can you add a little padding between the checkboxes and the text as per the screenshots above?

I will let @markherringer respond to your query.

**Comment by markherringer** [comment]
Hi @meomancer thanks for all the work you are putting in. Here is my feedback:

Please remove - all type of services
Please amend - 'full time equivalent doctors' to 'full time doctors'
Please amend - 'full time equivalent doctors' to 'full time nurses'

remove the 'and'

There is attribute that i am still confuse:
1. User can add 1 or more url?
I'm not sure which attribute you are refereing to? What is the number??
https://github.com/healthsites/healthsites/wiki/Healthsite-attributes


2. what is "
Note: Outpatient consultation and in-patient hospitalization"

This is a quoation mark. It is not meant to be included. It just indicates everything between the quotation marks.
Like..."this is the text to copy" = this is the text to copy

Note: I think a check box next to each option will be best. The user needs to know if the hosspital or clinic sends Doctors out to peoples homes and if there is place in the hospital or clinic for people to stay and receive treatment.
* Outpatient consultation
* In-patient hospitalization

**Comment by meomancer** [comment]
@markherringer, about the url, i thought because of url in http://healthsites.mashastudio.net/ has more than 1, the user can add 1 or more url.
I will change it. So user just can edit 1 url, isn't it?

**Comment by markherringer** [comment]
Hi @meomancer we need to be able to add two disctinct URLS for attributes 4 and 15.

https://github.com/healthsites/healthsites/wiki/Healthsite-attributes

1) a link to the raw data file (.csv ect)
2) Name and or website of the organisation supplying the data

Sometimes the organisation supplying the data makes the data available somewhere other than their home site. Like on a G drive.

**Comment by meomancer** [comment]
@markherringer is it can be edited?

**Comment by meomancer** [comment]
Latest Update Screenshot.

selection_023
- Was login as admin. Upload csv with 5 data. 
- Created North Jakarta Hospital in create mode in map
- Edited Feridhoo Health Center

selection_024
When "Feridhoo Health Center" clicked

selection_025
When "North Jakarta Hospital" clicked

**Comment by meomancer** [comment]
@markherringer 
@timlinux 
Need polishing from @MariaSolovyeva for the edit mode design
**REVIEW**
This big changes:
1. This are the attribute that can be changed (in edit and create mode)
selection_026
selection_027

2. User can add tags to a locality
screenshot from 2016-01-04 13 57 44

3. User can add other attributes, with some text
selection_028

4. It is saved. Latest update is working good.
selection_029


5. Latest updates is working good too in front end
selection_030

6. Latest udates is filtered too when filetring country
selection_031

**Comment by meomancer** [comment]
*Update 13* : last update in tag view
selection_032

Tagging now is not case sensitive. So "Healthsite" and "healthsite" are same tag.

**Comment by meomancer** [comment]
Map view by country. It can be access in Country data in front page.
Just click the name of country
selection_033

**Comment by timlinux** [comment]
@meomancer can you help to resolve the merge conflicts here please?

**Comment by meomancer** [comment]
hello @timlinux 
i already fixed conflicts and tested it

**Pull request merged**
