### PR TITLE
#243 | establish country data section

### PR DESCRIPTION
**Pull request by meomancer**
@timlinux @markherringer 
i have already implemented the functionality
can click the marker to redirect to map page
but, the map width is 100% and i don't know how to fit it to the div
i need help from @MariaSolovyeva

### CODE REVIEW

**Comment by timlinux** [comment]
Is this ready to merge now @meomancer ?

**Comment by timlinux** [comment]
I tested here on my local machine and the search box, chart and map are not interactive, but when I press enter on search it is giving a 500 error:

http://192.168.99.100:49361/search/localities/country?q=South+Africa

screen shot 2015-12-08 at 08 39 41

**Comment by meomancer** [comment]
@timlinux have you migrated it? because it needs migration, to load the country data first.

**Comment by meomancer** [comment]
@timlinux i rebuild HS from zero and found the problem. It is because we don't have GOOGLE_MAPS_API_KEY.
It needs for setup viewport of map. Already updated PR, if there is no GOOGLE_MAPS_API_KEY, the viewport will not changed.

**Pull request merged**
