### PR TITLE
#256 | Adding Contact Us Form 

### PR DESCRIPTION
**Pull request by meomancer**
@markherringer 
i added contact form, but the form view (it is using iframe) is already using background color. So, the design is different than the image

### CODE REVIEW

**Comment by timlinux** [comment]
@meomancer I think it will be better if we use 

http://django-envelope.readthedocs.org/en/stable/

rather than google forms. It will let us control the appearance more easily and keep the data close to the app.

Also your PR breaks DRY (don't repeat yourself)  - we should use template inheritance to include the base template and then add only the things needed specifically for the form.

**Comment by meomancer** [comment]
@timlinux 
already using base html (the old one is broken), and using django envelope

**Comment by meomancer** [comment]
@timlinux fixing import of base.html

**Comment by timlinux** [comment]
@meomancer there seem to be a lot of different things going on in the PR. Can you please separate them out into separate PR's? This PR should have only things relating to the contact form in it. Thanks! Don't forget we need migrations too....

**Pull request closed without merging**
