### PR TITLE
add flatpage for enrollment

### PR DESCRIPTION
**Pull request by ann26**
Screenshot from 2019-07-12 16-23-31

Screenshot from 2019-07-12 16-50-32

### CODE REVIEW

**Comment by ann26** [comment]
Added rich text format editor in admin:
Screenshot from 2019-07-16 12-02-45
Screenshot from 2019-07-16 12-09-24


Screenshot from 2019-07-16 12-06-18
Screenshot from 2019-07-16 12-07-00

**Comment by meomancer** [comment]
thank you very much @ann26 
i will continue in here by adding QR Code process

**Comment by meomancer** [comment]
Hi @timlinux @markherringer 
This PR is change enrollment as flatpage
how to create campaign page?

Go to here in admin
Selection_375

Create and admin will be like this (api key will show after the campaign page created)
Selection_372
We can edit any content as we want. The idea is we can put campaign description for each of campaign.
Gather url is odk url that will be used on od (the server url on odk)

To enter the campaign page, we can see it in navigation
Selection_376

The campaign page will show with content from admin
and also the templates also updated
Selection_373
Selection_374

**Comment by meomancer** [comment]
LGTM thank you @ann26

**Comment by meomancer** [comment]
hi @markherringer 
could you check this?
i need your input for the design of our first campaign

**Comment by markherringer** [comment]
Hi @meomancer @timlinux 
please could we discuss

**Pull request merged**
