### PR TITLE
Remove Django pre_delete signal inside social_user/models.py file

### PR DESCRIPTION
**Pull request by LeMeteore**
The pre_delete signal inside `social_user/models.py` was used to make sure that when a `TrustedUser` is deleted, the relateded `DataLoaderPermissions` will also be deleted. I guess, it was done that way, because, on the `DataLoaderPermission` model, there was a user attribute, linked to the `User` model via a ForeignKey.

My attempt here was to directly link the `DataLoaderPermission` model, to a `TrustedUser` via a ForeignKey, so that whenever the `TrustedUser` is deleted, the related `DataLoaderPermissions` will also be deleted, because that is the default [behaviour](https://docs.djangoproject.com/en/1.11/ref/models/fields/#foreignkey).

### CODE REVIEW

**Comment by dodobas** [comment]
I don't think that you can simply switch the models, `User.primary_key` is not the same as `TrustedUser.primary_key`. Did you forgot to add migration for this change?

You should also create a data migration which will correctly map User-> TrustedUser

**Comment by LeMeteore** [comment]
> I don't think that we can simply switch the models, User.primary_key is not the same as TrustedUser.primary_key. 
You're definitely right.

> Did you forgot to add migration for this change?
Mouarf, sorry. Just added them.

> You should also create a data migration which will correctly map User-> TrustedUser
Done.

**Comment by dodobas** [comment]
If you look at the failed Travis-CI build log (https://travis-ci.org/healthsites/healthsites/builds/237739472), there is a small issue of fixing flake8 errors. We have the `auto_clean.sh` script in the django_project folder which will autofix some of the errors (like isort errors).

The other error is related to the migration dependencies, seems like `localites` migrations are executed before `social_users` so we need to add a migration dependency to the new migration.

However the hidden, and more interesting problem, is the `AlterField` migration command. Because we simply alter the field in the database, it might fail because we can't ensure that User.id is the same as TrustedUser.id. Simply, it's not possible to ensure database relational integrity. Seems like we need to remove the referential integrity, update the data, and then enable the referential integrity, there might be other ways to do it.

Is TrustedUser process working in the Django Admin, did you test it?

**Comment by LeMeteore** [comment]
> If you look at the failed Travis-CI build log (https://travis-ci.org/healthsites/healthsites/builds/237739472), there is a small issue of fixing flake8 errors. We have the auto_clean.sh script in the django_project folder which will autofix some of the errors (like isort errors).

Still have some strange problems related to the installation of autopep8, but ok, no worries, I'll fix this part.

> The other error is related to the migration dependencies, seems like localites migrations are executed before social_users so we need to add a migration dependency to the new migration.

```
       operations = [                                                                                                       
           migrations.AlterField(                                                                                           
               model_name='dataloaderpermission',                                                                           
               name='uploader',                                                                                             
               field=models.ForeignKey(verbose_name=b'Uploader', to='social_users.TrustedUser', help_text=b'The user who    
   propose the data loader.'),                                                                                              
           ),                                                                                                               
           migrations.RunSQL(                                                                                               
             "update localities_dataloaderpermission set uploader_id=subq.id from (select id, user_id from                  
   social_users_trustedusers) as subq where localities_dataloaderpermission.uploader_id = subq.user_id"                     
           ),                                                                                                               
       ]  
```

Above is the actual migration script. Do you want to put the RunSQL before the AlterField? The real problem in my case, it that my TrustedUser table is empty. 

> However the hidden, and more interesting problem, is the AlterField migration command. Because we simply alter the field in the database, it might fail because we can't ensure that User.id is the same as TrustedUser.id. Simply, it's not possible to ensure database relational integrity. Seems like we need to remove the referential integrity, update the data, and then enable the referential integrity, there might be other ways to do it.

I was pretty sure my sql query was doing everything right :( `update localities_dataloaderpermission set uploader_id=subq.id from (select id, user_id from                  
   social_users_trustedusers) as subq where localities_dataloaderpermission.uploader_id = subq.user_id`

> Is TrustedUser process working in the Django Admin, did you test it?
I tested the process via the Django shell, I created few Users and feww TrustedUsers and few DataLoaderPermissions. It seems like everything were working nice.

Let me come back to you for that one, I've never opened the Django admin since I'm working on this project :) haha

**Pull request closed without merging**
