### PR TITLE
update api to use rest framework and update docs API

### PR DESCRIPTION
**Pull request by meomancer**
Preparing code to update API for aether
- Clean code to use RestFramework
- Create docs page to make it easier to try the API
- Add "facility list" api with some filtering

selection_055
selection_056

### CODE REVIEW

**Comment by timlinux** [comment]
Partial implementation for  https://github.com/healthsites/healthsites/issues/1018

**Comment by meomancer** [comment]
Will fix the travis test

PR updated: 
create view to merge osm data and healthsite

API:
selection_023

The admin:
selection_024

How admin detail looks
selection_025

and also able to import osm data from node and way
selection_026
selection_027

**Comment by meomancer** [comment]
hi @timlinux 
update PR (not deployed to staging)

add api key model. It can be generated on admin or on profile page (if user is staff)
selection_050

selection_047


API Example:
selection_048

Inject docs to use api-key
selection_049

**Comment by timlinux** [comment]
LGTM when tests pass please merge.

**Pull request merged**
