### PR TITLE
Continent data

### PR DESCRIPTION
**Pull request by meomancer**
this fix https://github.com/healthsites/healthsites/issues/1410
Add continent data on map
- statistic
- shapefile

Screenshoots
instead A-Z accordion, change to the continent (already make sure every country has continent)
Selection_018

Click the name of continent to enter it's page
Selection_020

Can download shapefile too
Selection_021

At the bottom pf page, there is country list of the continent
Selection_023

### CODE REVIEW

**Comment by markherringer** [comment]
Great work @meomancer !

The request for the content polygons was received as a request in support of the API and the shape files rather than the front end design. I'm not sure it makes sense to establish an accordion for the continents on the front end. Let's have a look at it on https://develop.healthsites.io/map 

The important thing is that this will support developers interested in running analysis on Africa and the continents. Great job.

**Comment by meomancer** [comment]
hi @markherringer 
it's also support for API
you can get data from the continent level

**Comment by timlinux** [comment]
Thank you @meomancer Looks great! Just take care of the spelling of "Healthsites" in your headings.

**Comment by meomancer** [comment]
ok @timlinux 
hi @markherringer @timlinux 
should we keep the country list per continent or revert back into by alphabet?

not sure how to access continent data on map if not from there

**Comment by markherringer** [comment]
Are you able to share an update to develop.healthsites.io? @nixilla ?

**Comment by meomancer** [comment]
> Thank you @meomancer Looks great! Just take care of the spelling of "Healthsites" in your headings.
> 
> image

hi @timlinux 
fixed in here : https://github.com/healthsites/healthsites/pull/1432
(found typo in name of function)

**Pull request merged**
