### PR TITLE
split address to multiple key

### PR DESCRIPTION
**Pull request by meomancer**
### WARNING! NEEDS TO REFETCH ALL OF DOCKER OSM DATABASE
To apply this change, if not, the server will always gives error
To refetch it
1. Delete database of osm
2. Delete volume of all docker osm
3. Redeploy docker osm

### CHANGES
change addr:full to use
- addr:housenumber
- addr:street
- addr:city
- addr:country
- addr:postalcode

The info of address
Selection_184

Updated form
Selection_185

When empty
Selection_187

Country can be selected and searched
Selection_186

My Example:
Selection_188

On OSM
Selection_189

Note:
i'm using master.apis.dev.openstreetmap.org to test
https://master.apis.dev.openstreetmap.org/node/4319572847#map=19/-6.95801/107.64781

### CODE REVIEW

**Comment by tyrasd** [comment]
One suggestion: It is normally not necessary to specify the country of an address, because it is most of the time obvious from its location inside of a country.

Also looking at https://master.apis.dev.openstreetmap.org/node/4319572847, it seems like the `addr:city` field has a wrong value of `Indonesia` rather than the actual name of the city (`Bandung`, I assume).

**Comment by meomancer** [comment]
thank you @tyrasd 
i'm sorry, i paste wrong url
https://master.apis.dev.openstreetmap.org/node/4319572849

this is the correct one  based on my test changes in here
https://user-images.githubusercontent.com/4530905/77432921-489d7700-6e11-11ea-8cb1-bd36e7a32479.png

**Comment by tyrasd** [comment]
ah yes, this one looks fine. :+1:

**Comment by meomancer** [comment]
UPDATE:
- Relayouting of address input
- Call nominatim to get suggestion of address

Selection_196

Demo: 
https://drive.google.com/file/d/19rCNDoiIUyMfjeGvuzhKqCzhVRRf7UYB/view?usp=sharing

**Comment by nixilla** [comment]
@meomancer this has been reverted, could you please created new PR, but this time against develop?

**Comment by meomancer** [comment]
hi @nixilla 
https://github.com/healthsites/healthsites/pull/1391

could you make develop as default? it's always to be master at default and sometimes i forget to change it

**Pull request merged**
