### PR TITLE
add share button and remove facebook twitter login

### LINKED ISSUE #1187: share button
As a user I would like to share healthsite locations and country pages to facebook and twitter using the social media share button 

image

### PR DESCRIPTION
**Pull request by ann26**
fix #1187 

Peek 2019-07-02 14-00

### CODE REVIEW

**Comment by timlinux** [comment]
Looks great - can you show the user experience after you select each of facebook and twitter?

**Comment by ann26** [comment]
sure @timlinux 

here's twitter share:
Peek 2019-07-02 15-08

facebook share:
Peek 2019-07-02 15-09

**Comment by ann26** [comment]
hi @timlinux what do you think?

**Comment by meomancer** [comment]
LGTM for now
needed for other ticket

**Comment by markherringer** [comment]
image

**Pull request merged**
